#!/usr/bin/env bash

## quality-gates: Run quality checks for deployment confidence
function task_quality_gates {
  task_fmt
  task_lint
  task_test_check
}

## fmt: apply automatic formatting
function task_fmt {
  npm run format
}

## fmt-check: apply automatic formatting
function task_fmt_check {
  npm run format -- --check
}

## lint: apply automatic formatting
function task_lint {
  npm run lint
}

## lint-check: apply automatic formatting
function task_lint_check {
  npm run lint -- --max-warnings 0
}

## run: run the frontend
function task_run {
  npm run dev
}

## test: start watched test session
function task_test {
  npm run test:unit
}

## test-check: run all tests in check-mode, without watcher
function task_test_check {
  npm run test:unit -- --run
  npm run build
  npm run test:e2e
}

## setup: install dev requirements
function task_setup {
  npm install
}

#-------- All task definitions go above this line --------#

# Bash Strict Mode - For details, see
# https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425
set -u     # Raise error when using undefined variables
set -e     # Raise error if any command has a non-zero exit status
# set -x   # Enable this optionally to print every command executed by bash
set -o pipefail  # Prevent pipelines from masking errors

function task_usage {
    echo "Usage: $0"
    sed -n 's/^##//p' <"$0" | column -t -s ':' |  sed -E $'s/^/\t/'
}

cmd=${1:-}
shift || true
resolved_command=$(echo "task_${cmd}" | sed 's/-/_/g')
if [[ "$(LC_ALL=C type -t "${resolved_command}")" == "function" ]]; then
    pushd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null
    ${resolved_command} "$@"
else
    task_usage
    if [ -n "${cmd}" ]; then
      echo "'$cmd' could not be resolved - please use one of the above tasks"
      exit 1
    fi
fi
