/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations['health_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health/database': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Db Health */
    get: operations['db_health_health_database_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/nodes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Nodes */
    get: operations['get_nodes_nodes_get']
    put?: never
    /** Add Node */
    post: operations['add_node_nodes_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/nodes/{node_uuid}/{tag_uuid}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Add Tag To Node */
    post: operations['add_tag_to_node_nodes__node_uuid___tag_uuid__post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/nodes/{uuid}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Node */
    get: operations['get_node_nodes__uuid__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/nodes/{node_uuid}/links': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Node Links */
    get: operations['get_node_links_nodes__node_uuid__links_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/nodes/tag/{tag_uuid}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Tag Nodes */
    get: operations['get_tag_nodes_nodes_tag__tag_uuid__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/links': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Links */
    get: operations['get_links_links_get']
    put?: never
    /** Add Link */
    post: operations['add_link_links_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/links/{uuid}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Link */
    get: operations['get_link_links__uuid__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tags': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Tags */
    get: operations['get_tags_tags_get']
    put?: never
    /** Add Tag */
    post: operations['add_tag_tags_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tags/{uuid}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Tag */
    get: operations['get_tag_tags__uuid__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tags/node/{node_uuid}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Node Tags */
    get: operations['get_node_tags_tags_node__node_uuid__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Auth:Jwt.Login */
    post: operations['auth_jwt_login_auth_login_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Auth:Jwt.Logout */
    post: operations['auth_jwt_logout_auth_logout_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Register:Register */
    post: operations['register_register_auth_register_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** Body_auth_jwt_login_auth_login_post */
    Body_auth_jwt_login_auth_login_post: {
      /** Grant Type */
      grant_type?: string | null
      /** Username */
      username: string
      /**
       * Password
       * Format: password
       */
      password: string
      /**
       * Scope
       * @default
       */
      scope: string
      /** Client Id */
      client_id?: string | null
      /**
       * Client Secret
       * Format: password
       */
      client_secret?: string | null
    }
    /** ErrorModel */
    ErrorModel: {
      /** Detail */
      detail:
        | string
        | {
            [key: string]: string
          }
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** LinkIn */
    LinkIn: {
      /** Node1 */
      node1: string
      /** Node2 */
      node2: string
      /** Type */
      type: string
      /** Annotation */
      annotation: string
    }
    /** LinkOut */
    LinkOut: {
      /**
       * Uuid
       * Format: uuid4
       */
      uuid: string
      type: components['schemas']['LinkType']
      /**
       * Node1
       * Format: uuid4
       */
      node1: string
      /**
       * Node2
       * Format: uuid4
       */
      node2: string
      /** Annotation */
      annotation: string
    }
    /**
     * LinkType
     * @enum {string}
     */
    LinkType: 'SYNONYM'
    /** NodeIn */
    NodeIn: {
      /** Term */
      term: string
      /** Definition */
      definition: string
      /** Tags */
      tags: string[]
    }
    /** NodeOut */
    NodeOut: {
      /**
       * Uuid
       * Format: uuid4
       */
      uuid: string
      /** Term */
      term: string
      /** Definition */
      definition: string
      /** Tags */
      tags: string[]
    }
    /** TagIn */
    TagIn: {
      /** Title */
      title: string
      /** Description */
      description: string
    }
    /** TagOut */
    TagOut: {
      /**
       * Uuid
       * Format: uuid4
       */
      uuid: string
      /** Title */
      title: string
      /** Description */
      description: string
    }
    /** UserCreate */
    UserCreate: {
      /**
       * Email
       * Format: email
       */
      email: string
      /** Password */
      password: string
      /**
       * Is Active
       * @default true
       */
      is_active: boolean | null
      /**
       * Is Superuser
       * @default false
       */
      is_superuser: boolean | null
      /**
       * Is Verified
       * @default false
       */
      is_verified: boolean | null
    }
    /** UserRead */
    UserRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Email
       * Format: email
       */
      email: string
      /**
       * Is Active
       * @default true
       */
      is_active: boolean
      /**
       * Is Superuser
       * @default false
       */
      is_superuser: boolean
      /**
       * Is Verified
       * @default false
       */
      is_verified: boolean
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  db_health_health_database_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  get_nodes_nodes_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NodeOut'][]
        }
      }
    }
  }
  add_node_nodes_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['NodeIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NodeOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  add_tag_to_node_nodes__node_uuid___tag_uuid__post: {
    parameters: {
      query?: never
      header?: never
      path: {
        node_uuid: string
        tag_uuid: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NodeOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_node_nodes__uuid__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        uuid: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NodeOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_node_links_nodes__node_uuid__links_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        node_uuid: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LinkOut'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_tag_nodes_nodes_tag__tag_uuid__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        tag_uuid: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NodeOut'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_links_links_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LinkOut'][]
        }
      }
    }
  }
  add_link_links_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LinkIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LinkOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_link_links__uuid__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        uuid: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LinkOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_tags_tags_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TagOut'][]
        }
      }
    }
  }
  add_tag_tags_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TagIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TagOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_tag_tags__uuid__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        uuid: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TagOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_node_tags_tags_node__node_uuid__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        node_uuid: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TagOut'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  auth_jwt_login_auth_login_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/x-www-form-urlencoded': components['schemas']['Body_auth_jwt_login_auth_login_post']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorModel']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  auth_jwt_logout_auth_logout_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Missing token or inactive user. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  register_register_auth_register_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserRead']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorModel']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
