"""Initial

Revision ID: b85ae5afb4e9
Revises:
Create Date: 2025-11-15 20:44:31.763892

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b85ae5afb4e9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lexloop_nodes",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "lexloop_tags",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "lexloop_links",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("annotation", sa.String(length=300), nullable=False),
        sa.Column("node1_uuid", sa.UUID(), nullable=False),
        sa.Column("node2_uuid", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["node1_uuid"],
            ["lexloop_nodes.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["node2_uuid"],
            ["lexloop_nodes.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "lexloop_node_to_tags",
        sa.Column("node_uuid", sa.UUID(), nullable=False),
        sa.Column("tag_uuid", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_uuid"],
            ["lexloop_nodes.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_uuid"],
            ["lexloop_tags.uuid"],
        ),
        sa.PrimaryKeyConstraint("node_uuid", "tag_uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lexloop_node_to_tags")
    op.drop_table("lexloop_links")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_table("lexloop_tags")
    op.drop_table("lexloop_nodes")
    # ### end Alembic commands ###
