name: Frontend Deployment

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/frontend.yml'
      - 'frontend/**'
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'
  workflow_dispatch: null

permissions:
  id-token: write
  contents: read

jobs:
  quality-gates:
    name: Quality Gates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'frontend/.node-version'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: cd frontend && npm ci

      - name: Format check
        run: ./frontend/do fmt-check

      - name: Linting
        run: ./frontend/do lint-check

      - name: Test
        run: ./frontend/do test-check

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist/
          retention-days: 7

  publish-dev:
    name: Publish to Dev
    runs-on: ubuntu-latest
    needs: quality-gates
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist/

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::465836752303:role/lexloop-cicd-deploy-role
          aws-region: eu-central-1

      - name: Upload to dev
        run: ./frontend/do publish dev
