name: Infrastructure Deployment

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/infrastructure.yml'
      - 'infrastructure/**'
  pull_request:
    branches: [main]
    paths:
      - 'infrastructure/**'
  workflow_dispatch: null

permissions:
  id-token: write
  contents: read

jobs:
  quality-gates:
    name: Quality Gates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::465836752303:role/lexloop-cicd-deploy-role
          aws-region: eu-central-1

      - name: Format check
        run: ./infrastructure/do fmt-check

      - name: Linting
        run: ./infrastructure/do lint

  deploy-dev:
    name: Deploy Dev Environment
    runs-on: ubuntu-latest
    needs: quality-gates
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build lambda bundle
        run: cd backend && ./do build

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::465836752303:role/lexloop-cicd-deploy-role
          aws-region: eu-central-1

      - name: Deploy dev environment
        run: |
          cd infrastructure
          ./do apply-auto dev
